spring:
  application:
    name: labor-protection-service
    
  profiles:
    active: local
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # 개발 단계에서는 create-drop, 운영 환경에서는 validate로 변경
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      
server:
  port: 8080
  servlet:
    context-path: /api
    
logging:
  level:
    root: INFO
    org.foreignworker.hackatone: DEBUG
    org.hibernate.SQL: DEBUG
    
# JWT 설정 (실제 사용 시 환경 변수나 외부 설정으로 관리)
jwt:
  secret: labor-protection-secret-key-must-be-at-least-64-characters-long-for-security-reasons 
  expiration-time: 86400000 # 24시간
  refresh-expiration-time: 2592000000 # 30일 